### ISSUE TITLE
Unable to pause game

### ISSUE THREAD

**Issue by Hunklol** [LlysiX/rock-band-2-deluxe#2]
Start button works for everything else in game except while playing a song. I recently downloaded for Xbox

**Comment by jnackmclain** [comment]
You have a plugin called nova that has a screenshot setting that overrides the pause botton in rb2. disable this setting and all is well.
Citation:
https://www.reddit.com/r/360hacks/comments/gpfamn/psa_disable_screenshots_in_aurora_if_the_start/
