### ISSUE TITLE
"Pad for Drums" modifier help

### ISSUE THREAD

**Issue by HideriFN** [LlysiX/rock-band-2-deluxe#4]
Playing with PS3 version.
1. List button used on this modifier? like L2 for this and X for that. (Kinda need WIKI about this)
2. When using this modifier, on gameplay I can't go to pause menu using START button, is this bug or what button used to pause the game?

**Comment by jnackmclain** [comment]
I don't know the default mappings. experiment in game to find out.
your pause issue sounds the same as #2
